# Generated by Django 2.0.3 on 2018-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('p_ttc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire TTC')),
            ],
        ),
    ]
